check if file exists

diff --git a/editconf b/editconf
--- a/editconf
+++ b/editconf
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
-
 help_string="edit nextcloud config.php"
+CFGFILE="/var/www/nextcloud/config/config.php"
+if [ ! -z $CFGFILE ]; then
+        vim ${CFGFILE}
+else
+        echo "### MISSING LOGFILE: ${CFGFILE}"
+        exit 1
+fi
 
-vim /var/www/nextcloud/config/config.php
diff --git a/showaudit b/showaudit
--- a/showaudit
+++ b/showaudit
@@ -1,3 +1,10 @@
 #!/usr/bin/bash
 help_string="Parse and list nextcloud audit.log entries"
-jq -r '[.time,.remoteAddr,.user,.method,.message] | @text' /var/log/nextcloud/audit.log
+LOGFILE="/var/log/nextcloud/audit.log"
+if [ ! -z $LOGFILE ]; then
+	jq -r '[.time,.remoteAddr,.user,.method,.message] | @text' ${LOGFILE}
+else
+        echo "### MISSING LOGFILE: ${LOGFILE}"
+        exit 1
+fi
+
diff --git a/showconf b/showconf
--- a/showconf
+++ b/showconf
@@ -1,3 +1,9 @@
 #!/usr/bin/env bash
 help_string="Show nextcloud config.php"
-cat /var/www/nextcloud/config/config.php
+CFGFILE="/var/www/nextcloud/config/config.php"
+if [ ! -z $CFGFILE ]; then
+        cat ${CFGFILE}
+else
+        echo "### MISSING LOGFILE: ${CFGFILE}"
+        exit 1
+fi
diff --git a/showfailedlogin b/showfailedlogin
--- a/showfailedlogin
+++ b/showfailedlogin
@@ -1,3 +1,11 @@
 #!/usr/bin/bash
 help_string="Show failed logins from nextcloud.log"
-jq -r '. | select(.message|type=="string") | select(.message | contains("Login"))' /var/log/nextcloud/nextcloud.log | jq -r '[.time,.message,.userAgent] | @text'
+
+LOGFILE="/var/log/nextcloud/nextcloud.log"
+if [ ! -z $LOGFILE ]; then
+	jq -r '. | select(.message|type=="string") | select(.message | contains("Login"))' ${LOGFILE} | jq -r '[.time,.message,.userAgent] | @text'
+else
+        echo "### MISSING LOGFILE: ${LOGFILE}"
+        exit 1
+fi
+
diff --git a/showlog b/showlog
--- a/showlog
+++ b/showlog
@@ -1,10 +1,15 @@
 #!/usr/bin/bash
 help_string="Parse and list nextcloud.log entries"
-
-### PRETTY OUTPUT
-if [ "$1" == "-p" ]; then
-	jq  '. | select(.message|type=="string")' /var/log/nextcloud/nextcloud.log | jq -r '[.time,.remoteAddr,.message] | @text'
+LOGFILE="/var/log/nextcloud/nextcloud.log"
+if [ ! -z $LOGFILE ]; then
+	### PRETTY OUTPUT
+	if [ "$1" == "-p" ]; then
+		jq  '. | select(.message|type=="string")' ${LOGFILE} | jq -r '[.time,.remoteAddr,.message] | @text'
+	else
+		jq . ${LOGFILE}
+		echo "### TRY RUNNING showlog -p"
+	fi
 else
-	jq . /var/log/nextcloud/nextcloud.log
-	echo "### TRY RUNNING showlog -p"
+        echo "### MISSING LOGFILE: ${LOGFILE}"
+        exit 1
 fi
diff --git a/showslowlog b/showslowlog
--- a/showslowlog
+++ b/showslowlog
@@ -1,3 +1,9 @@
 #!/usr/bin/bash
 help_string="Show mysql slow.log entries"
-tail -20f /var/log/mysql/slow.log
+LOGFILE="/var/log/mysql/slow.log"
+if [ ! -z $LOGFILE ]; then
+	tail -20f /var/log/mysql/slow.log
+else
+	echo "### MISSING LOGFILE: ${LOGFILE}"
+	exit 1
+fi
diff --git a/showusage b/showusage
--- a/showusage
+++ b/showusage
@@ -1,3 +1,9 @@
 #!/usr/bin/env bash
 help_string="Show disk usage on nextcloud/data directory"
-du -h -s /var/www/nextcloud/data/*
+DIR="/var/www/nextcloud/data"
+if [ -d $DIR ]; then
+	du -h -s ${DIR}/*
+else
+	echo "### MISSING DIRECTORY: ${DIR}"
+	exit 1
+fi
